version: 2
jobs:
  build:
    # Specify the Xcode version to use
    macos:
      xcode: "10.3.0"
    environment:
      FASTLANE_LANE: build_debug
    steps:
      - checkout
      # Specify Ruby version
      - run:
          name: Set Ruby Version
          command: echo "ruby-2.4.0" > ~/.ruby-version
      # Bundle
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      # Build app
      - run:
          name: Build
          command: bundle exec fastlane $FASTLANE_LANE --verbose