# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_version "2.121.1"
default_platform :ios
xcversion(version: "~> 10.3.0")

platform :ios do
  desc "Clean project"
  lane :clean do
    spm(
      command: "clean",
      build_path: "./build"
    )
  end

desc "Build Swift Package in debug mode"
  lane :build_debug do
    spm(
          command: "build",
          configuration: "debug"
      )
  end

  desc "Build Swift Package in release mode"
  lane :build_release do
    spm(
          command: "build",
          configuration: "release"
      )
  end

  desc "Run Unit test"
  lane :test do
    spm(
          command: "test"
      )
  end

end
